# ============================================
# Data Cleaning Pipeline
# ============================================

Pipeline de limpeza e padronização de dados aplicado ao dataset do catálogo da Netflix.

O processo inclui tratamento de valores nulos, remoção de duplicatas, padronização de categorias, transformação de tipos de dados e criação de novas variáveis para análise exploratória.

# 1) Importar bibliotecas

In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 2) Carregar dataset

In [38]:
df = pd.read_csv("NetFlix.csv")

# 3) Exploração inicial do dataset

In [39]:
# verificar primeiras linhas
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,14-Aug-20,2020,TV-MA,4,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,15-Dec-17,2008,TV-MA,143,"Horror Movies, International Movies, Thrillers",An architect and his wife move into a castle t...
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,5-Jan-19,2016,TV-PG,124,"Dramas, International Movies, Sports Movies",Three Indonesian women break records by becomi...
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,1-Mar-16,2016,R,90,Comedies,New NFL star Thad buys his old teammates' belo...
4,s1001,TV Show,Blue Planet II,NaN,David Attenborough,United Kingdom,3-Dec-18,2017,TV-G,1,"British TV Shows, Docuseries, Science & Nature TV",This sequel to the award-winning nature series...

In [40]:
# verificar estrutura dos dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   int64
 10  genres        7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(2), object(10)
memory usage: 730.2+ KB

In [41]:
# verificar estatísticas básicas
df.describe()

       release_year     duration
count   7787.000000  7787.000000
mean    2013.932580    69.122769
std        8.757395    50.950743
min     1925.000000     1.000000
25%     2013.000000     2.000000
50%     2017.000000    88.000000
75%     2018.000000   106.000000
max     2021.000000   312.000000

In [42]:
# verificar valores nulos
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
genres             0
description        0
dtype: int64

# 4) Remover duplicatas

In [43]:
# verificar se existem
df.duplicated().sum()

0

# 5) Tratar valores nulos

In [44]:
# diretor ausente
df["director"] = df["director"].fillna("Unknown")

# elenco ausente
df["cast"] = df["cast"].fillna("Not informed")

# país ausente
df["country"] = df["country"].fillna("Unknown")

# rating ausente
df["rating"] = df["rating"].fillna("Not Rated")

# remover linhas com data ausente (poucas)
df = df.dropna(subset=["date_added"])

# 6) Corrigir tipos de dados

In [45]:
# converter coluna de data
df["date_added"] = pd.to_datetime(df["date_added"])

# 7) Padronizar valores de texto

In [46]:
# remover espaços extras
df["country"] = df["country"].str.strip()

# padronizar formato
df["country"] = df["country"].str.title()

# padronizar gêneros
df["genres"] = df["genres"].str.strip()

# 8) Separar colunas compostas

In [69]:
# pegar apenas o primeiro país listado
df["country_main"] = df["country"].str.split(",").str[0]

# criar colunas para cada gênero
genres_dummies = df["genres"].str.get_dummies(sep=", ")

# juntar com o dataset original
df = pd.concat([df, genres_dummies], axis=1)

# deletar coluna de generos antiga
df = df.drop(columns=["genres"])

KeyError: 'genres'

# 9) Criar novas variáveis (feature engineering)

In [53]:
# ano que foi adicionado na plataforma
df["year_added"] = df["date_added"].dt.year

# mês que foi adicionado
df["month_added"] = df["date_added"].dt.month

# 10) Validar dados após limpeza

In [54]:
# verificar novamente nulos
df.isnull().sum()

show_id                0
type                   0
title                  0
director               0
cast                   0
                      ..
TV Sci-Fi & Fantasy    0
TV Shows               0
TV Thrillers           0
Teen TV Shows          0
Thrillers              0
Length: 97, dtype: int64

In [55]:
# verificar estrutura final
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7777 entries, 0 to 7786
Data columns (total 97 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   show_id                       7777 non-null   object
 1   type                          7777 non-null   object
 2   title                         7777 non-null   object
 3   director                      7777 non-null   object
 4   cast                          7777 non-null   object
 5   country                       7777 non-null   object
 6   date_added                    7777 non-null   datetime64[ns]
 7   release_year                  7777 non-null   int64
 8   rating                        7777 non-null   object
 9   duration                      7777 non-null   int64
 10  description                   7777 non-null   object
 11  Action & Adventure            7777 non-null   int64
 12  Anime Features                7777 non-null   int64
 13  Anime Series                  7777 non-null   int64
 14  British TV Shows              7777 non-null   int64
 15  Children & Family Movies      7777 non-null   int64
 16  Classic & Cult TV             7777 non-null   int64
 17  Classic Movies                7777 non-null   int64
 18  Comedies                      7777 non-null   int64
 19  Crime TV Shows                7777 non-null   int64
 20  Cult Movies                   7777 non-null   int64
 21  Documentaries                 7777 non-null   int64
 22  Docuseries                    7777 non-null   int64
 23  Dramas                        7777 non-null   int64
 24  Faith & Spirituality          7777 non-null   int64
 25  Horror Movies                 7777 non-null   int64
 26  Independent Movies            7777 non-null   int64
 27  International Movies          7777 non-null   int64
 28  International TV Shows        7777 non-null   int64
 29  Kids' TV                      7777 non-null   int64
 30  Korean TV Shows               7777 non-null   int64
 31  LGBTQ Movies                  7777 non-null   int64
 32  Movies                        7777 non-null   int64
 33  Music & Musicals              7777 non-null   int64
 34  Reality TV                    7777 non-null   int64
 35  Romantic Movies               7777 non-null   int64
 36  Romantic TV Shows             7777 non-null   int64
 37  Sci-Fi & Fantasy              7777 non-null   int64
 38  Science & Nature TV           7777 non-null   int64
 39  Spanish-Language TV Shows     7777 non-null   int64
 40  Sports Movies                 7777 non-null   int64
 41  Stand-Up Comedy               7777 non-null   int64
 42  Stand-Up Comedy & Talk Shows  7777 non-null   int64
 43  TV Action & Adventure         7777 non-null   int64
 44  TV Comedies                   7777 non-null   int64
 45  TV Dramas                     7777 non-null   int64
 46  TV Horror                     7777 non-null   int64
 47  TV Mysteries                  7777 non-null   int64
 48  TV Sci-Fi & Fantasy           7777 non-null   int64
 49  TV Shows                      7777 non-null   int64
 50  TV Thrillers                  7777 non-null   int64
 51  Teen TV Shows                 7777 non-null   int64
 52  Thrillers                     7777 non-null   int64
 53  year_added                    7777 non-null   int64
 54  month_added                   7777 non-null   int64
 55  Action & Adventure            7777 non-null   int64
 56  Anime Features                7777 non-null   int64
 57  Anime Series                  7777 non-null   int64
 58  British TV Shows              7777 non-null   int64
 59  Children & Family Movies      7777 non-null   int64
 60  Classic & Cult TV             7777 non-null   int64
 61  Classic Movies                7777 non-null   int64
 62  Comedies                      7777 non-null   int64
 63  Crime TV Shows                7777 non-null   int64
 64  Cult Movies                   7777 non-null   int64
 65  Documentaries                 7777 non-null   int64
 66  Docuseries                    7777 non-null   int64
 67  Dramas                        7777 non-null   int64
 68  Faith & Spirituality          7777 non-null   int64
 69  Horror Movies                 7777 non-null   int64
 70  Independent Movies            7777 non-null   int64
 71  International Movies          7777 non-null   int64
 72  International TV Shows        7777 non-null   int64
 73  Kids' TV                      7777 non-null   int64
 74  Korean TV Shows               7777 non-null   int64
 75  LGBTQ Movies                  7777 non-null   int64
 76  Movies                        7777 non-null   int64
 77  Music & Musicals              7777 non-null   int64
 78  Reality TV                    7777 non-null   int64
 79  Romantic Movies               7777 non-null   int64
 80  Romantic TV Shows             7777 non-null   int64
 81  Sci-Fi & Fantasy              7777 non-null   int64
 82  Science & Nature TV           7777 non-null   int64
 83  Spanish-Language TV Shows     7777 non-null   int64
 84  Sports Movies                 7777 non-null   int64
 85  Stand-Up Comedy               7777 non-null   int64
 86  Stand-Up Comedy & Talk Shows  7777 non-null   int64
 87  TV Action & Adventure         7777 non-null   int64
 88  TV Comedies                   7777 non-null   int64
 89  TV Dramas                     7777 non-null   int64
 90  TV Horror                     7777 non-null   int64
 91  TV Mysteries                  7777 non-null   int64
 92  TV Sci-Fi & Fantasy           7777 non-null   int64
 93  TV Shows                      7777 non-null   int64
 94  TV Thrillers                  7777 non-null   int64
 95  Teen TV Shows                 7777 non-null   int64
 96  Thrillers                     7777 non-null   int64
dtypes: datetime64[ns](1), int64(88), object(8)
memory usage: 5.8+ MB

In [56]:
# visualizar dataset final
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,TV Action & Adventure,TV Comedies,TV Dramas,TV Horror,TV Mysteries,TV Sci-Fi & Fantasy,TV Shows,TV Thrillers,Teen TV Shows,Thrillers
0,s1,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4,...,0,0,1,0,0,1,0,0,0,0
1,s10,Movie,1920,Vikram Bhatt,"Rajneesh Duggal, Adah Sharma, Indraneil Sengup...",India,2017-12-15,2008,TV-MA,143,...,0,0,0,0,0,0,0,0,0,1
2,s100,Movie,3 Heroines,Iman Brotoseno,"Reza Rahadian, Bunga Citra Lestari, Tara Basro...",Indonesia,2019-01-05,2016,TV-PG,124,...,0,0,0,0,0,0,0,0,0,0
3,s1000,Movie,Blue Mountain State: The Rise of Thadland,Lev L. Spiro,"Alan Ritchson, Darin Brooks, James Cade, Rob R...",United States,2016-03-01,2016,R,90,...,0,0,0,0,0,0,0,0,0,0
4,s1001,TV Show,Blue Planet II,Unknown,David Attenborough,United Kingdom,2018-12-03,2017,TV-G,1,...,0,0,0,0,0,0,0,0,0,0